// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIELcVP92urJ2hY6DtZrtMv1rCmyQ_o9I',
    appId: '1:1031364853932:web:1e8063710f892e84cddf09',
    messagingSenderId: '1031364853932',
    projectId: 're-exam-8c7de',
    authDomain: 're-exam-8c7de.firebaseapp.com',
    storageBucket: 're-exam-8c7de.appspot.com',
    measurementId: 'G-LJJ023QC9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-xaFgP3Ln0C9SVXCymx6LtE66PEt4XYA',
    appId: '1:1031364853932:android:20bea04e75372824cddf09',
    messagingSenderId: '1031364853932',
    projectId: 're-exam-8c7de',
    storageBucket: 're-exam-8c7de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaheHuepOn65h3C1OrduJbEK3oI0oiFGo',
    appId: '1:1031364853932:ios:5f0470165608e303cddf09',
    messagingSenderId: '1031364853932',
    projectId: 're-exam-8c7de',
    storageBucket: 're-exam-8c7de.appspot.com',
    iosBundleId: 'com.example.reExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaheHuepOn65h3C1OrduJbEK3oI0oiFGo',
    appId: '1:1031364853932:ios:5f0470165608e303cddf09',
    messagingSenderId: '1031364853932',
    projectId: 're-exam-8c7de',
    storageBucket: 're-exam-8c7de.appspot.com',
    iosBundleId: 'com.example.reExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIELcVP92urJ2hY6DtZrtMv1rCmyQ_o9I',
    appId: '1:1031364853932:web:7f5ac9d10a97ffa1cddf09',
    messagingSenderId: '1031364853932',
    projectId: 're-exam-8c7de',
    authDomain: 're-exam-8c7de.firebaseapp.com',
    storageBucket: 're-exam-8c7de.appspot.com',
    measurementId: 'G-050TBDKHZP',
  );
}
